### ISSUE TITLE
How to migrate easy from JFlex?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [coconut2015/cookcc#28]
```
I am looking for JFlex successor, a project that would be maintained and where 
performances will be significantly better the JFlex.

I have flex files for JFlex, how easy is to migrate to cookcc?

How mature the current version is?

Thank you!
```

Original issue reported on code.google.com by `igor.spasic` on 10 Dec 2013 at 12:42

**Comment by coconut2015** [comment]
CookCC is pretty stable.  I use it a lot to write utilities at work.

As for JFlex, I do not plan to write any tools for it.  There is no point and no reason and no point to do so.  The file format is archiac and difficult to read / maintain.

It would be far better for you to migrate to Java annotation based approach used by CookCC which is far superior in terms of maintenance and ease of use.
