### ISSUE TITLE
constant string too long

### ISSUE THREAD

**Issue by puntogil** [coconut2015/cookcc#29]
hi
any ideas?
thanks in advance
_classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javacBUILD/cookcc-9264b6d80a9a4ee639a8aede2e62bd5b55e5cb66/src/org/yuanheng/cookcc/lexer/PatternScanner.java:70: error: constant string too long
    [javac]             private static char[] ecs = ("\000\000\000\000\000\000\000\000\000\001\002\000\000\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\001\000\004\000\005\000\000\006\007\010\011\012\013\014\015\016\017\017\017\017\017\017\017\017\017\017\020\000\021\000\022\023\000\024\024\024\024\025\026\027\027\027\027\027\027\027\027\030\027\027\027\027\027\027\027\027\027\027\027\031\032\033\034\035\000\024\024\024\024\024\024\027\027\027\027\027\027\027\027\027\027\027\027\027\027\036\027\027\037\027\027\040\041\042\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000" + "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000" + "\000\043").toCharArray ();
    [javac]                                         ^
    [javac] 1 error
    [javac] 1 warning

**Comment by coconut2015** [comment]
It has to compiled with ecj.  jdk javac has a limitation that the total string resource length in utf8 has to be under 64k. Notice the total word. Such limitation does not exist in java class specification.

**Comment by puntogil** [comment]
hi
i used
$ java -version
openjdk version "1.8.0_51"
OpenJDK Runtime Environment (build 1.8.0_51-b16)
OpenJDK Server VM (build 25.51-b03, mixed mode)

**Comment by coconut2015** [comment]
I did a bit more test.  JDK / OpenJDK has the following interesting thing:
1. Within one string expression, the total string length needs to be smaller than 65534.
2. There can be multiple strings that each can reach to that limit.

So, I will change my strategy a bit to avoid having all the string in one expression.  This is a quite a bit complicated for template approach.  So in the mean time, just use ECJ (Eclipse Java Compiler) to make the build.

**Comment by coconut2015** [comment]
Done.  See commit d4354efd653a5bdd82550be35b9a6ea2d50da84a
